name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Install tools
        run: |
          set -e

          # Install terraform-docs
          echo "Installing terraform-docs..."
          TERRAFORM_DOCS_VERSION="v0.17.0"
          wget -q -O terraform-docs.tar.gz "https://github.com/terraform-docs/terraform-docs/releases/download/${TERRAFORM_DOCS_VERSION}/terraform-docs-${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz"
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/terraform-docs

          # Install actionlint
          echo "Installing actionlint..."
          ACTIONLINT_VERSION="1.7.7"
          wget -q -O actionlint.tar.gz "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
          tar -xzf actionlint.tar.gz
          chmod +x actionlint
          sudo mv actionlint /usr/local/bin/actionlint

      - name: Verify tools installation
        run: |
          echo "Verifying installed tools..."
          python --version
          terraform --version
          terraform-docs --version
          actionlint -version

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: powershell-syntax-check,powershell-whitespace-cleanup,powershell-script-analyzer,pester-tests-quick,terraform_tflint,commitizen
          PRE_COMMIT_HOME: ~/.cache/pre-commit
