name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Install PowerShell
        run: |
          # Update package list
          sudo apt-get update
          # Install prerequisites
          sudo apt-get install -y wget apt-transport-https software-properties-common
          # Download and install PowerShell
          UBUNTU_VERSION=$(lsb_release -rs)
          wget -q "https://packages.microsoft.com/config/ubuntu/${UBUNTU_VERSION}/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Install PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -ErrorAction SilentlyContinue
          Install-Module -Name Pester -Force -Scope CurrentUser -ErrorAction SilentlyContinue

      - name: Install additional tools
        run: |
          # Install terraform-docs
          ARCH=$(uname)
          curl -sSLo ./terraform-docs.tar.gz "https://terraform-docs.io/dl/v0.17.0/terraform-docs-v0.17.0-${ARCH}-amd64.tar.gz"
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/terraform-docs

          # Install tflint
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

          # Install actionlint
          bash <(curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          sudo mv actionlint /usr/local/bin/

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: powershell-whitespace-cleanup,powershell-script-analyzer,pester-tests-quick,terraform_tflint,commitizen
          PRE_COMMIT_HOME: ~/.cache/pre-commit
